name: "Update Copyright Year in License"

on:
  push:
    branches:
      - isaacs/copyright-year-action
      - main
  workflow_dispatch:

jobs:
  license-copyright-year:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: print all dates
        run: bash .github/workflows/copyright-year.sh
      - name: check in licenses if modified
        run: |
          bash .github/workflows/commit-if-modified.sh \
            "license-year-bot@example.com" \
            "License Year Bot" \
            "chore: add copyright year to license" \
            LICENSE*
